### ISSUE TITLE
Refact: 알림 도메인 entity, service, repository 수정 및 리팩토링

### ISSUE THREAD

**Issue by weightsforfun** [DOROEDU/Doro-Server#94]
## 📌 Feature Issue
알림 도메인 오류 수정 및 리팩토링

## 📝 To-do
- [x] Notification Entity 수정
- [x] Notification Service 수정 및 리팩토링
- [x] Notification API 리팩토링
- [x] Notification Repository 수정 및 리팩토링
- [x] Notification 도메인 테스트
- [x] 안드로이드 알림 전송 테스트
- [x] iOS 알림 전송 테스트

## ETC
> 로직 완성 후 ios, android 민혁쌤이랑 같이 테스트 후 issue 종료
